### PR TITLE
HOTFIX: Lumi should not be touched, as we need to assume that it is...

### PR DESCRIPTION
**Pull request by HeinerTholen**
…correctly given in the original config and files are added in the end. This only concers NEventsBreak-mode, not FileSplit-mode.

I've only tested the master branch.

### CODE REVIEW

**Comment by dgonzal** [comment]
in eventsbreak mode you can not use the normal normalisation. if you do it the weights will be all wrong! checked that the way it is implemented now, the weights are all the same for serial sframe_main, pod-lite sframe_main & sframe_batch. 

To be a bit more specific, sframe asumes if you just use n events from one process, that it is what you are going to use for the complete process and scales up the MC. So if you split up your file into 10 jobs you will get a factor of 10 (not exactly because the last job normaly has less events). A safeguard for DATA could be added.

**Comment by dgonzal** [comment]
To have a look at the current status have a look at /nfs/dust/cms/user/gonvaq/CMSSW/CMSSW_7_4_15_patch1/src/UHH2/VLQToTopAndLepton/Utils/plots/sframeRatio.ps as you see there are exactly the same apart from some very small rounding errors.

**Comment by dgonzal** [comment]
to see the current status I have a ratio plot at /nfs/dust/cms/user/gonvaq/CMSSW/CMSSW_7_4_15_patch1/src/UHH2/VLQToTopAndLepton/Utils/plots/sframeRatio.ps As you can see they match apart from very very small rounding errors.

**Comment by HeinerTholen** [comment]
Nope, for me, sframe did not do any special kind of scaling. In fact, with the fix that I'm proposing, it's producing the correct results. The lumi in the xml file for one job is exactly the same as in the full config. After summing up the histograms from all jobs, the final histograms have the right normalization.

**Comment by HeinerTholen** [comment]
This is my config:
https://github.com/UHH2/VLQToHiggsAndLepton/blob/master/config/VLQToHiggsAndLepton.xml

Maybe there's a special switch for the sframe feature you are talking about?

**Comment by dgonzal** [comment]
As discussed this has to do with the use_sframe_weights=true. And will be fixed soon

**Pull request closed without merging**
