### PR TITLE
fhadd and symlinks

### PR DESCRIPTION
**Pull request by HeinerTholen**
I didn't have fhadd installed, so it crashed. With the fix I give you an example on how can support both, users with and without fhadd.

The other patch makes symlinks to config files work (the path needs to be resolved in order for xmllint to resolve entities).

The PR is intended for master, but I saw that you've got the development branch now. Is it for feature development, or do you want everything to go there? (These patches are tested... by me. =)

### CODE REVIEW

**Comment by HeinerTholen** [comment]
further addendum:
if resubmit is requested, the output of qstat is checked. If some jobs are still running, the user is asked, if she/he really wants to resubmit.

**Comment by dgonzal** [comment]
hey fhadd will not get into the code since it only copies th1 and not the trees, sorry for the import that I forgot. 
If things are stable they should go into the master. dev is just for stuff I'm/ some one else is trying out and not yet ready, but nice to have.

**Comment by HeinerTholen** [comment]
ok, so let me fix that up..

**Comment by HeinerTholen** [comment]
It is important that fhadd is not imported, since I don't have it installed.. =)

**Comment by dgonzal** [comment]
yeah its just one python file that could be added to the repo but it is not useful

**Pull request merged**
